#!/bin/bash
# ============================================================================
# Parameter Sweep Batch Script for Geant4 Scintillator Detector
# Author: Auto-generated
# Date: 2026-01-31
# ============================================================================
#
# This script automatically loops through geometry parameters, runs
# simulations, and stores results in separate folders.
#
# Usage: Edit configuration section below, then run: ./run_batch.sh
# ============================================================================

# ============================================================================
# CONFIGURATION SECTION - Edit these values
# ============================================================================

# --- Parameter Loop Configuration (true/false) ---
LOOP_ARRAY_NX=false
LOOP_ARRAY_NY=false
LOOP_ARRAY_NZ=false
LOOP_CRYSTAL_GAP=true
LOOP_CRYSTAL_SIZE=false
LOOP_CRYSTAL_SIZE_Y=false
LOOP_FILLTER_RATIO_Y=false
LOOP_FILLTER_RATIO_Z=false
LOOP_FILLTER_POS_RATIO_Y=false
LOOP_FILLTER_POS_RATIO_Z=false
LOOP_SURFACE_SIGMA=false

# --- Parameter Range Configuration ---
# Array Nx (crystal count in x direction)
NX_START=11
NX_END=11
NX_STEP=1

# Array Ny (crystal count in y direction)
NY_START=7
NY_END=7
NY_STEP=1

# Array Nz (crystal count in z direction)
NZ_START=7
NZ_END=7
NZ_STEP=1

# Crystal Gap (in mm, 0 means continuous no-gap packing)
GAP_START=0.0
GAP_END=0.0
GAP_STEP=0.1

# Crystal Size (x/z dimension, in mm)
SIZE_START=3
SIZE_END=3
SIZE_STEP=1

# Crystal Size Y (y dimension, in mm)
SIZE_Y_START=3
SIZE_Y_END=3
SIZE_Y_STEP=1

# Fillter Ratio Y (0-1, size ratio in Y)
FILLTER_RATIO_Y_START=0.3
FILLTER_RATIO_Y_END=0.3
FILLTER_RATIO_Y_STEP=0.1

# Fillter Ratio Z (0-1, size ratio in Z)
FILLTER_RATIO_Z_START=1.0
FILLTER_RATIO_Z_END=1.0
FILLTER_RATIO_Z_STEP=0.1

# Fillter Position Ratio Y (0-1, position ratio in Y)
FILLTER_POS_RATIO_Y_START=0.7
FILLTER_POS_RATIO_Y_END=0.7
FILLTER_POS_RATIO_Y_STEP=0.1

# Fillter Position Ratio Z (0-1, position ratio in Z)
FILLTER_POS_RATIO_Z_START=0.0
FILLTER_POS_RATIO_Z_END=0.0
FILLTER_POS_RATIO_Z_STEP=0.1

# Surface Sigma (0-1, crystal optical surface roughness)
SIGMA_START=0.5
SIGMA_END=0.7
SIGMA_STEP=0.1

# --- Default Values (used when parameter is not looping) ---
DEFAULT_NX=11
DEFAULT_NY=7
DEFAULT_NZ=7
DEFAULT_GAP=0.0
DEFAULT_SIZE=3
DEFAULT_SIZE_Y=3
DEFAULT_FILLTER_RATIO_Y=0.3
DEFAULT_FILLTER_RATIO_Z=1.0
DEFAULT_FILLTER_POS_RATIO_Y=0.7
DEFAULT_FILLTER_POS_RATIO_Z=0.0
DEFAULT_SURFACE_SIGMA=0.5

# --- Run Configuration ---
RUN_MACRO=run4.mac
EXE_PATH=build/Release/exampleB1

# --- Folder Naming Configuration (true/false) ---
NAME_INCLUDE_NX=false
NAME_INCLUDE_NY=false
NAME_INCLUDE_NZ=false
NAME_INCLUDE_GAP=true
NAME_INCLUDE_SIZE=false
NAME_INCLUDE_SIZE_Y=false
NAME_INCLUDE_FILLTER_RATIO_Y=false
NAME_INCLUDE_FILLTER_RATIO_Z=false
NAME_INCLUDE_FILLTER_POS_RATIO_Y=false
NAME_INCLUDE_FILLTER_POS_RATIO_Z=false
NAME_INCLUDE_SURFACE_SIGMA=false

# --- Geant4 Environment (adjust to your installation) ---
# Uncomment and adjust the path if needed:
# source /path/to/geant4-install/bin/geant4.sh

# ============================================================================
# END OF CONFIGURATION - Do not edit below unless you know what you're doing
# ============================================================================

echo "============================================================================"
echo "Parameter Sweep Batch Script"
echo "============================================================================"
echo ""

# Check if executable exists
if [ ! -f "$EXE_PATH" ]; then
    echo "ERROR: Executable not found at $EXE_PATH"
    echo "Please build the project first."
    exit 1
fi

# Create Results directory
mkdir -p Results

# Initialize loop counter
LOOP_COUNT=0

# Function to generate decimal sequence
generate_decimal_seq() {
    local start=$1
    local end=$2
    local step=$3
    awk -v start="$start" -v end="$end" -v step="$step" '
        BEGIN {
            for (i = start; i <= end + 0.001; i += step) {
                printf "%.1f\n", i
            }
        }'
}

# Function to generate geometry.mac
generate_geometry_mac() {
    local nx=$1
    local ny=$2
    local nz=$3
    local gap=$4
    local size=$5
    local size_y=$6
    local fillter_ratio_y=$7
    local fillter_ratio_z=$8
    local fillter_pos_ratio_y=$9
    local fillter_pos_ratio_z=${10}
    local surface_sigma=${11}
    
    cat > geometry.mac <<EOF
# Geometry macro: crystal array and gap (run before /run/initialize)
# Auto-generated by run_batch.sh
#
# Crystal array (nx, ny, nz)
/detector/arrayNx $nx
/detector/arrayNy $ny
/detector/arrayNz $nz
#
# Crystal gap in mm (0 means continuous no-gap packing)
/detector/crystalGap $gap mm
#
# Single crystal size (x/z), in mm
/detector/crystalSize $size mm
#
# Single crystal size in y, in mm
/detector/crystalSizeY $size_y mm
#
# Fillter (gap filler) parameters (ratios 0-1)
/detector/fillterRatioY $fillter_ratio_y
/detector/fillterRatioZ $fillter_ratio_z
/detector/fillterPosRatioY $fillter_pos_ratio_y
/detector/fillterPosRatioZ $fillter_pos_ratio_z
#
# Crystal optical surface roughness (0-1)
/detector/surfaceSigma $surface_sigma
EOF
}

# Start parameter sweep
echo "Starting parameter sweep..."
echo ""

# Build parameter lists
if [ "$LOOP_ARRAY_NX" = "true" ]; then
    NX_LIST=$(seq $NX_START $NX_STEP $NX_END)
else
    NX_LIST=$DEFAULT_NX
fi

if [ "$LOOP_ARRAY_NY" = "true" ]; then
    NY_LIST=$(seq $NY_START $NY_STEP $NY_END)
else
    NY_LIST=$DEFAULT_NY
fi

if [ "$LOOP_ARRAY_NZ" = "true" ]; then
    NZ_LIST=$(seq $NZ_START $NZ_STEP $NZ_END)
else
    NZ_LIST=$DEFAULT_NZ
fi

if [ "$LOOP_CRYSTAL_GAP" = "true" ]; then
    GAP_LIST=$(generate_decimal_seq $GAP_START $GAP_END $GAP_STEP)
else
    GAP_LIST=$DEFAULT_GAP
fi

if [ "$LOOP_CRYSTAL_SIZE" = "true" ]; then
    SIZE_LIST=$(generate_decimal_seq $SIZE_START $SIZE_END $SIZE_STEP)
else
    SIZE_LIST=$DEFAULT_SIZE
fi

if [ "$LOOP_CRYSTAL_SIZE_Y" = "true" ]; then
    SIZE_Y_LIST=$(generate_decimal_seq $SIZE_Y_START $SIZE_Y_END $SIZE_Y_STEP)
else
    SIZE_Y_LIST=$DEFAULT_SIZE_Y
fi

if [ "$LOOP_FILLTER_RATIO_Y" = "true" ]; then
    FILLTER_RATIO_Y_LIST=$(generate_decimal_seq $FILLTER_RATIO_Y_START $FILLTER_RATIO_Y_END $FILLTER_RATIO_Y_STEP)
else
    FILLTER_RATIO_Y_LIST=$DEFAULT_FILLTER_RATIO_Y
fi

if [ "$LOOP_FILLTER_RATIO_Z" = "true" ]; then
    FILLTER_RATIO_Z_LIST=$(generate_decimal_seq $FILLTER_RATIO_Z_START $FILLTER_RATIO_Z_END $FILLTER_RATIO_Z_STEP)
else
    FILLTER_RATIO_Z_LIST=$DEFAULT_FILLTER_RATIO_Z
fi

if [ "$LOOP_FILLTER_POS_RATIO_Y" = "true" ]; then
    FILLTER_POS_RATIO_Y_LIST=$(generate_decimal_seq $FILLTER_POS_RATIO_Y_START $FILLTER_POS_RATIO_Y_END $FILLTER_POS_RATIO_Y_STEP)
else
    FILLTER_POS_RATIO_Y_LIST=$DEFAULT_FILLTER_POS_RATIO_Y
fi

if [ "$LOOP_FILLTER_POS_RATIO_Z" = "true" ]; then
    FILLTER_POS_RATIO_Z_LIST=$(generate_decimal_seq $FILLTER_POS_RATIO_Z_START $FILLTER_POS_RATIO_Z_END $FILLTER_POS_RATIO_Z_STEP)
else
    FILLTER_POS_RATIO_Z_LIST=$DEFAULT_FILLTER_POS_RATIO_Z
fi

if [ "$LOOP_SURFACE_SIGMA" = "true" ]; then
    SIGMA_LIST=$(generate_decimal_seq $SIGMA_START $SIGMA_END $SIGMA_STEP)
else
    SIGMA_LIST=$DEFAULT_SURFACE_SIGMA
fi

# Nested loops through all parameter combinations
for surface_sigma in $SIGMA_LIST; do
for nx in $NX_LIST; do
    for ny in $NY_LIST; do
        for nz in $NZ_LIST; do
            for gap in $GAP_LIST; do
                for size in $SIZE_LIST; do
                    for size_y in $SIZE_Y_LIST; do
                        for fillter_ratio_y in $FILLTER_RATIO_Y_LIST; do
                            for fillter_ratio_z in $FILLTER_RATIO_Z_LIST; do
                                for fillter_pos_ratio_y in $FILLTER_POS_RATIO_Y_LIST; do
                                    for fillter_pos_ratio_z in $FILLTER_POS_RATIO_Z_LIST; do
                                        LOOP_COUNT=$((LOOP_COUNT + 1))
                                        
                                        # Build folder name with zero-padded counter
                                        FOLDER_NAME=$(printf "%03d" $LOOP_COUNT)
                                        
                                        [ "$NAME_INCLUDE_NX" = "true" ] && FOLDER_NAME="${FOLDER_NAME}_Nx${nx}"
                                        [ "$NAME_INCLUDE_NY" = "true" ] && FOLDER_NAME="${FOLDER_NAME}_Ny${ny}"
                                        [ "$NAME_INCLUDE_NZ" = "true" ] && FOLDER_NAME="${FOLDER_NAME}_Nz${nz}"
                                        [ "$NAME_INCLUDE_GAP" = "true" ] && FOLDER_NAME="${FOLDER_NAME}_Gap${gap}"
                                        [ "$NAME_INCLUDE_SIZE" = "true" ] && FOLDER_NAME="${FOLDER_NAME}_Size${size}"
                                        [ "$NAME_INCLUDE_SIZE_Y" = "true" ] && FOLDER_NAME="${FOLDER_NAME}_SizeY${size_y}"
                                        [ "$NAME_INCLUDE_FILLTER_RATIO_Y" = "true" ] && FOLDER_NAME="${FOLDER_NAME}_FRY${fillter_ratio_y}"
                                        [ "$NAME_INCLUDE_FILLTER_RATIO_Z" = "true" ] && FOLDER_NAME="${FOLDER_NAME}_FRZ${fillter_ratio_z}"
                                        [ "$NAME_INCLUDE_FILLTER_POS_RATIO_Y" = "true" ] && FOLDER_NAME="${FOLDER_NAME}_FPRY${fillter_pos_ratio_y}"
                                        [ "$NAME_INCLUDE_FILLTER_POS_RATIO_Z" = "true" ] && FOLDER_NAME="${FOLDER_NAME}_FPRZ${fillter_pos_ratio_z}"
                                        [ "$NAME_INCLUDE_SURFACE_SIGMA" = "true" ] && FOLDER_NAME="${FOLDER_NAME}_Sigma${surface_sigma//./p}"
                                        
                                        RESULT_DIR="Results/$FOLDER_NAME"
                                        
                                        echo "[$LOOP_COUNT] Running: Nx=$nx Ny=$ny Nz=$nz Gap=$gap Size=$size SizeY=$size_y FillterY=$fillter_ratio_y FillterZ=$fillter_ratio_z FPosY=$fillter_pos_ratio_y FPosZ=$fillter_pos_ratio_z Sigma=$surface_sigma"
                                        echo "   Output: $RESULT_DIR"
                                        
                                        # Generate geometry.mac
                                        generate_geometry_mac $nx $ny $nz $gap $size $size_y $fillter_ratio_y $fillter_ratio_z $fillter_pos_ratio_y $fillter_pos_ratio_z $surface_sigma
                                        
                                        # Create result folder
                                        mkdir -p "$RESULT_DIR"
                                        
                                        # Copy geometry.mac to result folder
                                        cp geometry.mac "$RESULT_DIR/geometry.mac"
                                        
                                        # Run simulation
                                        ./"$EXE_PATH" "$RUN_MACRO" > /dev/null 2>&1
                                        
                                        # Move CSV files to result folder
                                        for csv_file in AnaEx01_nt_*.csv; do
                                            if [ -f "$csv_file" ]; then
                                                mv "$csv_file" "$RESULT_DIR/" 2> /dev/null
                                            fi
                                        done
                                        
                                        echo "   Completed."
                                        echo ""
                                    done
                                done
                            done
                        done
                    done
                done
            done
        done
    done
done
done

echo "============================================================================"
echo "Parameter sweep completed!"
echo "Total runs: $LOOP_COUNT"
echo "Results saved in: Results/"
echo "============================================================================"
